const en = {
  open: 'Bank library', title: 'My saved banks', intro: 'Choose a saved bank to load into workspace bank {{bank}}.', saveCurrent: 'Save workspace bank {{bank}}', snapshotHelp: 'This creates an independent snapshot of all 32 sounds and their FM1 effects.', name: 'Bank name', namePlaceholder: 'e.g. Gig – Saturday', description: 'Description (optional)', descriptionPlaceholder: 'Notes about this bank', save: 'Save bank', loadBank: 'Load bank', editDetails: 'Edit bank details', update: 'Update details', savedBanks: 'Saved banks', count: '{{count}} saved bank', count_other: '{{count}} saved banks', search: 'Search saved banks', loading: 'Loading saved banks…', empty: 'No named banks yet. Save the selected workspace bank to create one.', noMatches: 'No saved banks match this search.', load: 'Load', updatedAt: 'Updated {{date}}', rename: 'Edit {{name}}', download: 'Download {{name}} as SysEx', downloadAction: 'Download SysEx file', duplicate: 'Duplicate {{name}}', duplicateAction: 'Duplicate bank', delete: 'Delete {{name}}', deleteAction: 'Delete bank', deleteConfirm: 'Permanently delete “{{name}}” from this browser?', operationFailed: 'The saved-bank operation failed.', saved: 'Saved “{{name}}”.', updated: 'Updated “{{name}}”.', downloaded: 'Downloaded “{{name}}”.', copied: 'Created “{{name}}”.', deleted: 'Deleted “{{name}}”.', loaded: 'Loaded “{{name}}” into workspace bank {{bank}}.', untitled: 'Untitled', workspaceName: 'Workspace bank {{bank}} name', editWorkspaceName: 'Rename bank',
}

const fr = {
  open: 'Bibliothèque de banques', title: 'Mes banques enregistrées', intro: 'Choisissez une banque enregistrée à charger dans la banque de travail {{bank}}.', saveCurrent: 'Enregistrer la banque de travail {{bank}}', snapshotHelp: 'Crée une copie indépendante des 32 sons et de leurs effets FM1.', name: 'Nom de la banque', namePlaceholder: 'ex. Concert – samedi', description: 'Description (facultative)', descriptionPlaceholder: 'Notes sur cette banque', save: 'Enregistrer la banque', loadBank: 'Charger une banque', editDetails: 'Modifier les détails', update: 'Mettre à jour', savedBanks: 'Banques enregistrées', count: '{{count}} banque enregistrée', count_other: '{{count}} banques enregistrées', search: 'Rechercher des banques', loading: 'Chargement des banques…', empty: 'Aucune banque nommée. Enregistrez la banque de travail sélectionnée pour en créer une.', noMatches: 'Aucune banque enregistrée ne correspond à cette recherche.', load: 'Charger', updatedAt: 'Modifiée le {{date}}', rename: 'Modifier {{name}}', download: 'Télécharger {{name}} au format SysEx', downloadAction: 'Télécharger le fichier SysEx', duplicate: 'Dupliquer {{name}}', duplicateAction: 'Dupliquer la banque', delete: 'Supprimer {{name}}', deleteAction: 'Supprimer la banque', deleteConfirm: 'Supprimer définitivement « {{name}} » de ce navigateur ?', operationFailed: 'L’opération sur la banque enregistrée a échoué.', saved: '« {{name}} » enregistrée.', updated: '« {{name}} » mise à jour.', downloaded: '« {{name}} » téléchargée.', copied: '« {{name}} » créée.', deleted: '« {{name}} » supprimée.', loaded: '« {{name}} » chargée dans la banque de travail {{bank}}.', untitled: 'Sans titre', workspaceName: 'Nom de la banque de travail {{bank}}', editWorkspaceName: 'Renommer la banque',
}

const es = {
  open: 'Biblioteca de bancos', title: 'Mis bancos guardados', intro: 'Elige un banco guardado para cargarlo en el banco de trabajo {{bank}}.', saveCurrent: 'Guardar banco de trabajo {{bank}}', snapshotHelp: 'Crea una copia independiente de los 32 sonidos y sus efectos FM1.', name: 'Nombre del banco', namePlaceholder: 'p. ej., Concierto – sábado', description: 'Descripción (opcional)', descriptionPlaceholder: 'Notas sobre este banco', save: 'Guardar banco', loadBank: 'Cargar banco', editDetails: 'Editar detalles', update: 'Actualizar detalles', savedBanks: 'Bancos guardados', count: '{{count}} banco guardado', count_other: '{{count}} bancos guardados', search: 'Buscar bancos guardados', loading: 'Cargando bancos guardados…', empty: 'Aún no hay bancos con nombre. Guarda el banco de trabajo seleccionado para crear uno.', noMatches: 'Ningún banco guardado coincide con la búsqueda.', load: 'Cargar', updatedAt: 'Actualizado el {{date}}', rename: 'Editar {{name}}', download: 'Descargar {{name}} como SysEx', downloadAction: 'Descargar archivo SysEx', duplicate: 'Duplicar {{name}}', duplicateAction: 'Duplicar banco', delete: 'Eliminar {{name}}', deleteAction: 'Eliminar banco', deleteConfirm: '¿Eliminar permanentemente “{{name}}” de este navegador?', operationFailed: 'La operación del banco guardado ha fallado.', saved: '“{{name}}” guardado.', updated: '“{{name}}” actualizado.', downloaded: '“{{name}}” descargado.', copied: '“{{name}}” creado.', deleted: '“{{name}}” eliminado.', loaded: '“{{name}}” cargado en el banco de trabajo {{bank}}.', untitled: 'Sin título', workspaceName: 'Nombre del banco de trabajo {{bank}}', editWorkspaceName: 'Renombrar banco',
}

const de = {
  open: 'Bankbibliothek', title: 'Meine gespeicherten Bänke', intro: 'Wähle eine gespeicherte Bank für Arbeitsbank {{bank}} aus.', saveCurrent: 'Arbeitsbank {{bank}} speichern', snapshotHelp: 'Erstellt eine unabhängige Kopie aller 32 Sounds und ihrer FM1-Effekte.', name: 'Bankname', namePlaceholder: 'z. B. Auftritt – Samstag', description: 'Beschreibung (optional)', descriptionPlaceholder: 'Notizen zu dieser Bank', save: 'Bank speichern', loadBank: 'Bank laden', editDetails: 'Bankdetails bearbeiten', update: 'Details aktualisieren', savedBanks: 'Gespeicherte Bänke', count: '{{count}} gespeicherte Bank', count_other: '{{count}} gespeicherte Bänke', search: 'Gespeicherte Bänke durchsuchen', loading: 'Gespeicherte Bänke werden geladen…', empty: 'Noch keine benannten Bänke. Speichere die ausgewählte Arbeitsbank, um eine anzulegen.', noMatches: 'Keine gespeicherte Bank entspricht der Suche.', load: 'Laden', updatedAt: 'Aktualisiert am {{date}}', rename: '{{name}} bearbeiten', download: '{{name}} als SysEx herunterladen', downloadAction: 'SysEx-Datei herunterladen', duplicate: '{{name}} duplizieren', duplicateAction: 'Bank duplizieren', delete: '{{name}} löschen', deleteAction: 'Bank löschen', deleteConfirm: '„{{name}}“ dauerhaft aus diesem Browser löschen?', operationFailed: 'Der Vorgang für die gespeicherte Bank ist fehlgeschlagen.', saved: '„{{name}}“ gespeichert.', updated: '„{{name}}“ aktualisiert.', downloaded: '„{{name}}“ heruntergeladen.', copied: '„{{name}}“ erstellt.', deleted: '„{{name}}“ gelöscht.', loaded: '„{{name}}“ in Arbeitsbank {{bank}} geladen.', untitled: 'Ohne Titel', workspaceName: 'Name der Arbeitsbank {{bank}}', editWorkspaceName: 'Bank umbenennen',
}

const ptBR = {
  open: 'Biblioteca de bancos', title: 'Meus bancos salvos', intro: 'Escolha um banco salvo para carregar no banco de trabalho {{bank}}.', saveCurrent: 'Salvar banco de trabalho {{bank}}', snapshotHelp: 'Cria uma cópia independente dos 32 sons e de seus efeitos do FM1.', name: 'Nome do banco', namePlaceholder: 'ex.: Show – sábado', description: 'Descrição (opcional)', descriptionPlaceholder: 'Observações sobre este banco', save: 'Salvar banco', loadBank: 'Carregar banco', editDetails: 'Editar detalhes', update: 'Atualizar detalhes', savedBanks: 'Bancos salvos', count: '{{count}} banco salvo', count_other: '{{count}} bancos salvos', search: 'Pesquisar bancos salvos', loading: 'Carregando bancos salvos…', empty: 'Ainda não há bancos com nome. Salve o banco de trabalho selecionado para criar um.', noMatches: 'Nenhum banco salvo corresponde à pesquisa.', load: 'Carregar', updatedAt: 'Atualizado em {{date}}', rename: 'Editar {{name}}', download: 'Baixar {{name}} como SysEx', downloadAction: 'Baixar arquivo SysEx', duplicate: 'Duplicar {{name}}', duplicateAction: 'Duplicar banco', delete: 'Excluir {{name}}', deleteAction: 'Excluir banco', deleteConfirm: 'Excluir “{{name}}” permanentemente deste navegador?', operationFailed: 'A operação do banco salvo falhou.', saved: '“{{name}}” salvo.', updated: '“{{name}}” atualizado.', downloaded: '“{{name}}” baixado.', copied: '“{{name}}” criado.', deleted: '“{{name}}” excluído.', loaded: '“{{name}}” carregado no banco de trabalho {{bank}}.', untitled: 'Sem título', workspaceName: 'Nome do banco de trabalho {{bank}}', editWorkspaceName: 'Renomear banco',
}

const zhHans = {
  open: '音色库', title: '我保存的音色库', intro: '选择一个已保存的音色库，加载到工作区音色库 {{bank}}。', saveCurrent: '保存工作区音色库 {{bank}}', snapshotHelp: '创建包含全部 32 个音色及其 FM1 效果的独立副本。', name: '音色库名称', namePlaceholder: '例如：周六演出', description: '说明（可选）', descriptionPlaceholder: '此音色库的备注', save: '保存音色库', loadBank: '加载音色库', editDetails: '编辑音色库信息', update: '更新信息', savedBanks: '已保存的音色库', count: '已保存 {{count}} 个音色库', count_other: '已保存 {{count}} 个音色库', search: '搜索已保存的音色库', loading: '正在加载已保存的音色库…', empty: '还没有命名音色库。保存当前工作区音色库即可创建。', noMatches: '没有符合搜索条件的已保存音色库。', load: '加载', updatedAt: '更新于 {{date}}', rename: '编辑 {{name}}', download: '将 {{name}} 下载为 SysEx', downloadAction: '下载 SysEx 文件', duplicate: '复制 {{name}}', duplicateAction: '复制音色库', delete: '删除 {{name}}', deleteAction: '删除音色库', deleteConfirm: '要从此浏览器永久删除“{{name}}”吗？', operationFailed: '已保存音色库的操作失败。', saved: '已保存“{{name}}”。', updated: '已更新“{{name}}”。', downloaded: '已下载“{{name}}”。', copied: '已创建“{{name}}”。', deleted: '已删除“{{name}}”。', loaded: '已将“{{name}}”加载到工作区音色库 {{bank}}。', untitled: '未命名', workspaceName: '工作区音色库 {{bank}} 名称', editWorkspaceName: '重命名音色库',
}

export const namedBankResources = { de, en, es, fr, ptBR, zhHans }
