const en = {
  auditionGroup: 'Operator {{number}} audition', mute: 'Mute', unmute: 'Unmute', solo: 'Solo', unsolo: 'Unsolo', auditionAction: '{{action}} operator {{number}} for audition', auditionTemporary: '{{action}} operator {{number}} temporarily', auditionConnect: '{{action}} operator {{number}}; connect MIDI to hear audition changes', operatorOutput: 'Operator {{number}} output level',
  oscillator: 'Oscillator', mode: 'Mode', coarse: 'Coarse', fine: 'Fine', detune: 'Detune', keyboardScaling: 'Scaling', breakpoint: 'Breakpoint', depth: 'Depth', left: 'Left', right: 'Right', rateScaling: 'Rate scaling', leftCurve: 'Left curve', rightCurve: 'Right curve', velocity: 'Velocity', ampModSensitivity: 'Amp mod sens.',
  envelopeInstruction: 'Drag a point; arrows adjust, Shift moves by 10.', editableEnvelope: 'Editable four-stage amplitude envelope', lfoWave: 'LFO wave', dx7Algorithm: 'DX7 algorithm', unsavedBody: 'Save this working copy to the browser library, or discard it and restore the saved sound on the FM1.', revertTitle: 'Discard every edit since the last library save and restore that sound on the FM1',
  keyboard: 'Keyboard', pianoKeyboard: 'Piano keyboard', dragKeyboard: 'Drag keyboard', closeKeyboard: 'Close keyboard', shiftOctave: 'Shift octave {{direction}}', playNote: 'Play {{note}}', performance: 'PERFORMANCE', directionDown: 'down', directionUp: 'up', enableEffect: 'Enable {{effect}}', bypassEffect: 'Bypass {{effect}}', effectState: '{{effect}}: {{state}}', bypassed: 'bypassed',
  effects: { filter: 'Filter', reverb: 'Reverb', delay: 'Delay', distortion: 'Distortion', chorus: 'Chorus', phaser: 'Phaser' }, parameters: { type: 'Type', cutoff: 'Cutoff', resonance: 'Resonance', space: 'Space', decay: 'Decay', mix: 'Mix', rate: 'Rate', gain: 'Gain', tone: 'Tone', level: 'Level', frequency: 'Frequency' }, options: { lowPass: 'Low pass', bandPass: 'Band pass', highPass: 'High pass', room: 'Room', hall: 'Hall', plate: 'Plate' },
}

export const uiResources = {
  en: { ui: en },
  fr: { ui: { ...en,
    auditionGroup: 'Écoute de l’opérateur {{number}}', mute: 'Couper', unmute: 'Rétablir', solo: 'Solo', unsolo: 'Désactiver solo', auditionAction: '{{action}} l’opérateur {{number}} pour l’écoute', auditionTemporary: '{{action}} temporairement l’opérateur {{number}}', auditionConnect: '{{action}} l’opérateur {{number}} ; connectez le MIDI pour entendre les changements', operatorOutput: 'Niveau de sortie de l’opérateur {{number}}', oscillator: 'Oscillateur', coarse: 'Grossier', fine: 'Fin', detune: 'Désaccord', keyboardScaling: 'Suivi du clavier', breakpoint: 'Point de coupure', depth: 'Profondeur', left: 'Gauche', right: 'Droite', rateScaling: 'Suivi de vitesse', leftCurve: 'Courbe gauche', rightCurve: 'Courbe droite', velocity: 'Vélocité', ampModSensitivity: 'Sens. mod. amplitude', envelopeInstruction: 'Faites glisser un point ; les flèches ajustent, Maj déplace de 10.', editableEnvelope: 'Enveloppe d’amplitude modifiable à quatre étapes', lfoWave: 'Forme d’onde LFO', dx7Algorithm: 'Algorithme DX7', unsavedBody: 'Enregistrez cette copie dans la bibliothèque du navigateur, ou abandonnez-la et restaurez le son enregistré sur le FM1.', revertTitle: 'Abandonner toutes les modifications depuis le dernier enregistrement et restaurer ce son sur le FM1', keyboard: 'Clavier', pianoKeyboard: 'Clavier piano', dragKeyboard: 'Déplacer le clavier', closeKeyboard: 'Fermer le clavier', shiftOctave: 'Décaler l’octave vers le {{direction}}', playNote: 'Jouer {{note}}', directionDown: 'bas', directionUp: 'haut', enableEffect: 'Activer {{effect}}', bypassEffect: 'Contourner {{effect}}', effectState: '{{effect}} : {{state}}', bypassed: 'contourné', effects: { filter: 'Filtre', reverb: 'Réverbération', delay: 'Délai', distortion: 'Distorsion', chorus: 'Chorus', phaser: 'Phaser' }, parameters: { type: 'Type', cutoff: 'Coupure', resonance: 'Résonance', space: 'Espace', decay: 'Déclin', mix: 'Mixage', rate: 'Vitesse', gain: 'Gain', tone: 'Tonalité', level: 'Niveau', frequency: 'Fréquence' }, options: { lowPass: 'Passe-bas', bandPass: 'Passe-bande', highPass: 'Passe-haut', room: 'Pièce', hall: 'Salle', plate: 'Plaque' },
  } },
  es: { ui: { ...en,
    auditionGroup: 'Prueba del operador {{number}}', mute: 'Silenciar', unmute: 'Activar sonido', unsolo: 'Quitar solo', auditionAction: '{{action}} el operador {{number}} para probarlo', auditionTemporary: '{{action}} temporalmente el operador {{number}}', auditionConnect: '{{action}} el operador {{number}}; conecta MIDI para oír los cambios', operatorOutput: 'Nivel de salida del operador {{number}}', oscillator: 'Oscilador', coarse: 'Grueso', fine: 'Fino', detune: 'Desafinación', keyboardScaling: 'Escalado de teclado', breakpoint: 'Punto de división', depth: 'Profundidad', left: 'Izquierda', right: 'Derecha', rateScaling: 'Escalado de velocidad', leftCurve: 'Curva izquierda', rightCurve: 'Curva derecha', velocity: 'Velocidad', ampModSensitivity: 'Sens. mod. amplitud', envelopeInstruction: 'Arrastra un punto; las flechas ajustan y Mayús desplaza 10.', editableEnvelope: 'Envolvente de amplitud editable de cuatro etapas', lfoWave: 'Forma de onda LFO', dx7Algorithm: 'Algoritmo DX7', unsavedBody: 'Guarda esta copia en la biblioteca del navegador o descártala y restaura el sonido guardado en el FM1.', revertTitle: 'Descartar todos los cambios desde el último guardado y restaurar ese sonido en el FM1', keyboard: 'Teclado', pianoKeyboard: 'Teclado de piano', dragKeyboard: 'Mover el teclado', closeKeyboard: 'Cerrar el teclado', shiftOctave: 'Desplazar octava hacia {{direction}}', playNote: 'Tocar {{note}}', performance: 'INTERPRETACIÓN', directionDown: 'abajo', directionUp: 'arriba', enableEffect: 'Activar {{effect}}', bypassEffect: 'Omitir {{effect}}', effectState: '{{effect}}: {{state}}', bypassed: 'omitido', effects: { filter: 'Filtro', reverb: 'Reverberación', delay: 'Retardo', distortion: 'Distorsión', chorus: 'Coro', phaser: 'Fáser' }, parameters: { type: 'Tipo', cutoff: 'Corte', resonance: 'Resonancia', space: 'Espacio', decay: 'Caída', mix: 'Mezcla', rate: 'Velocidad', gain: 'Ganancia', tone: 'Tono', level: 'Nivel', frequency: 'Frecuencia' }, options: { lowPass: 'Paso bajo', bandPass: 'Paso banda', highPass: 'Paso alto', room: 'Sala pequeña', hall: 'Sala', plate: 'Placa' },
  } },
  de: { ui: { ...en,
    auditionGroup: 'Operator {{number}} vorhören', mute: 'Stumm', unmute: 'Ton an', unsolo: 'Solo aus', auditionAction: 'Operator {{number}} zum Vorhören {{action}}', auditionTemporary: 'Operator {{number}} vorübergehend {{action}}', auditionConnect: 'Operator {{number}} {{action}}; MIDI verbinden, um Änderungen zu hören', operatorOutput: 'Ausgangspegel von Operator {{number}}', oscillator: 'Oszillator', coarse: 'Grob', fine: 'Fein', detune: 'Verstimmung', keyboardScaling: 'Tastaturskalierung', breakpoint: 'Trennpunkt', depth: 'Tiefe', left: 'Links', right: 'Rechts', rateScaling: 'Ratenskalierung', leftCurve: 'Linke Kurve', rightCurve: 'Rechte Kurve', velocity: 'Anschlagstärke', ampModSensitivity: 'Empf. Amplitudenmod.', envelopeInstruction: 'Punkt ziehen; Pfeile ändern, Umschalt bewegt um 10.', editableEnvelope: 'Editierbare vierstufige Amplitudenhüllkurve', lfoWave: 'LFO-Wellenform', dx7Algorithm: 'DX7-Algorithmus', unsavedBody: 'Diese Arbeitskopie in der Browser-Bibliothek speichern oder verwerfen und den gespeicherten Klang auf dem FM1 wiederherstellen.', revertTitle: 'Alle Änderungen seit dem letzten Speichern verwerfen und den Klang auf dem FM1 wiederherstellen', keyboard: 'Tastatur', pianoKeyboard: 'Klaviatur', dragKeyboard: 'Klaviatur verschieben', closeKeyboard: 'Klaviatur schließen', shiftOctave: 'Oktave nach {{direction}} verschieben', playNote: '{{note}} spielen', directionDown: 'unten', directionUp: 'oben', enableEffect: '{{effect}} aktivieren', bypassEffect: '{{effect}} umgehen', effectState: '{{effect}}: {{state}}', bypassed: 'umgangen', effects: { filter: 'Filter', reverb: 'Hall', delay: 'Delay', distortion: 'Verzerrung', chorus: 'Chorus', phaser: 'Phaser' }, parameters: { type: 'Typ', cutoff: 'Grenzfrequenz', resonance: 'Resonanz', space: 'Raum', decay: 'Abklingzeit', mix: 'Mix', rate: 'Rate', gain: 'Verstärkung', tone: 'Klang', level: 'Pegel', frequency: 'Frequenz' }, options: { lowPass: 'Tiefpass', bandPass: 'Bandpass', highPass: 'Hochpass', room: 'Raum', hall: 'Halle', plate: 'Platte' },
  } },
  ptBR: { ui: { ...en,
    auditionGroup: 'Audição do operador {{number}}', mute: 'Silenciar', unmute: 'Ativar som', unsolo: 'Desativar solo', auditionAction: '{{action}} o operador {{number}} para audição', auditionTemporary: '{{action}} temporariamente o operador {{number}}', auditionConnect: '{{action}} o operador {{number}}; conecte o MIDI para ouvir as alterações', operatorOutput: 'Nível de saída do operador {{number}}', oscillator: 'Oscilador', coarse: 'Grosso', fine: 'Fino', detune: 'Desafinação', keyboardScaling: 'Escalonamento do teclado', breakpoint: 'Ponto de divisão', depth: 'Profundidade', left: 'Esquerda', right: 'Direita', rateScaling: 'Escalonamento de taxa', leftCurve: 'Curva esquerda', rightCurve: 'Curva direita', velocity: 'Velocidade', ampModSensitivity: 'Sens. mod. amplitude', envelopeInstruction: 'Arraste um ponto; as setas ajustam e Shift move 10.', editableEnvelope: 'Envelope de amplitude editável de quatro estágios', lfoWave: 'Forma de onda LFO', dx7Algorithm: 'Algoritmo DX7', unsavedBody: 'Salve esta cópia na biblioteca do navegador ou descarte-a e restaure o som salvo no FM1.', revertTitle: 'Descartar todas as edições desde o último salvamento e restaurar o som no FM1', keyboard: 'Teclado', pianoKeyboard: 'Teclado de piano', dragKeyboard: 'Mover o teclado', closeKeyboard: 'Fechar o teclado', shiftOctave: 'Deslocar oitava para {{direction}}', playNote: 'Tocar {{note}}', directionDown: 'baixo', directionUp: 'cima', enableEffect: 'Ativar {{effect}}', bypassEffect: 'Ignorar {{effect}}', effectState: '{{effect}}: {{state}}', bypassed: 'ignorado', effects: { filter: 'Filtro', reverb: 'Reverberação', delay: 'Delay', distortion: 'Distorção', chorus: 'Chorus', phaser: 'Phaser' }, parameters: { type: 'Tipo', cutoff: 'Corte', resonance: 'Ressonância', space: 'Espaço', decay: 'Decaimento', mix: 'Mix', rate: 'Taxa', gain: 'Ganho', tone: 'Timbre', level: 'Nível', frequency: 'Frequência' }, options: { lowPass: 'Passa-baixas', bandPass: 'Passa-faixa', highPass: 'Passa-altas', room: 'Sala', hall: 'Salão', plate: 'Placa' },
  } },
  zhHans: { ui: { ...en,
    auditionGroup: '试听操作器 {{number}}', mute: '静音', unmute: '取消静音', unsolo: '取消独奏', auditionAction: '{{action}}操作器 {{number}} 以试听', auditionTemporary: '暂时{{action}}操作器 {{number}}', auditionConnect: '{{action}}操作器 {{number}}；连接 MIDI 后可听到变化', operatorOutput: '操作器 {{number}} 输出电平', oscillator: '振荡器', coarse: '粗调', fine: '微调', detune: '失谐', keyboardScaling: '键盘缩放', breakpoint: '分界点', depth: '深度', left: '左侧', right: '右侧', rateScaling: '速率缩放', leftCurve: '左曲线', rightCurve: '右曲线', velocity: '力度', ampModSensitivity: '幅度调制灵敏度', envelopeInstruction: '拖动节点；方向键微调，Shift 键每次移动 10。', editableEnvelope: '可编辑的四阶段幅度包络', lfoWave: 'LFO 波形', dx7Algorithm: 'DX7 算法', unsavedBody: '将此工作副本保存到浏览器音色库，或放弃更改并在 FM1 上恢复已保存的音色。', revertTitle: '放弃上次保存后的所有编辑，并在 FM1 上恢复该音色', keyboard: '键盘', pianoKeyboard: '钢琴键盘', dragKeyboard: '移动键盘', closeKeyboard: '关闭键盘', shiftOctave: '将八度向{{direction}}移动', playNote: '演奏 {{note}}', performance: '演奏', directionDown: '下', directionUp: '上', enableEffect: '启用{{effect}}', bypassEffect: '旁通{{effect}}', effectState: '{{effect}}：{{state}}', bypassed: '已旁通', effects: { filter: '滤波器', reverb: '混响', delay: '延迟', distortion: '失真', chorus: '合唱', phaser: '移相器' }, parameters: { type: '类型', cutoff: '截止频率', resonance: '共振', space: '空间', decay: '衰减', mix: '混合', rate: '速率', gain: '增益', tone: '音色', level: '电平', frequency: '频率' }, options: { lowPass: '低通', bandPass: '带通', highPass: '高通', room: '房间', hall: '大厅', plate: '板式' },
  } },
} as const
