#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# FM-1+VA controller hardware tests (docs/fm1-va-controller-tests.md), V1 to V8, the repeat run,
# and clean-up. It sends only the sound-setting CCs 24-31, 52-57, and 70-78 through
# scripts/send-fm1-va-sound-cc.c, which refuses every other controller, and it checks each one
# again here. It never sends CC 85-119, which press the FM1's own controls, and never SysEx.
#
#   scripts/run-fm1-va-controller-tests.sh                 # from the start
#   scripts/run-fm1-va-controller-tests.sh --from V4       # resume at a test
#   scripts/run-fm1-va-controller-tests.sh --from V2:53    # resume V2 at one controller
#
# Sections: prep V1 V2 V3 V4 V5 V6 V8 repeat V7 cleanup (V7 runs last because it writes the test
# preset). Answers and the bytes sent go to a Markdown ledger in docs/hardware-runs/.

TOTAL_STAGES=50
SECTIONS="prep V1 V2 V3 V4 V5 V6 V8 repeat V7 cleanup"
# The Envelope controllers come last, because the first of them switches the Envelope on (V5).
V2_CONTROLLERS="24:Waveform 25:Super 26:Detune 27:Drift 28:Sub 29:Noise 30:PWM 31:Filter_Type
52:Filter_Envelope 53:Filter_Decay 54:Filter_Shape 55:Filter_Velocity 56:Filter_Key_Tracking
57:LFO_to_Cutoff 71:Resonance 74:Cutoff 76:LFO_Speed 77:LFO_Pitch_Mod_Depth 78:LFO_Delay
70:Sustain 72:Release 73:Attack 75:Decay"

FROM_SECTION=prep
FROM_CC=""
while (($#)); do
  case "$1" in
    --from)
      [[ $# -ge 2 ]] || { printf 'Usage: %s [--from SECTION[:CC]]\n' "$0" >&2; exit 2; }
      FROM_SECTION="${2%%:*}"
      [[ "$2" == *:* ]] && FROM_CC="${2#*:}"
      shift 2
      ;;
    -h | --help)
      printf 'Usage: %s [--from SECTION[:CC]]\nSections: %s\n' "$0" "$SECTIONS"
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      exit 2
      ;;
  esac
done

section_index() {
  local index=0 name
  for name in $SECTIONS; do
    [[ "$name" == "$1" ]] && { printf '%s' "$index"; return 0; }
    index=$((index + 1))
  done
  return 1
}
START_INDEX=$(section_index "$FROM_SECTION") || {
  printf 'Unknown section %s. Sections: %s\n' "$FROM_SECTION" "$SECTIONS" >&2
  exit 2
}

if [[ -n "$FROM_CC" && ( "$FROM_SECTION" != V2 || " $V2_CONTROLLERS " != *" $FROM_CC:"* ) ]]; then
  printf 'Resume at a controller only within V2, with one of: %s\n' \
    "$(printf '%s ' $V2_CONTROLLERS | sed 's/:[^ ]*//g')" >&2
  exit 2
fi

cd "$(dirname "$0")/.."
LEDGER_DIR="${LEDGER_DIR:-docs/hardware-runs}"
mkdir -p "$LEDGER_DIR"
# The run's remembered answers (destination, firmware, ledger), so a resumed run picks them up.
ENV_FILE="$LEDGER_DIR/.fm1-va-controller-run.env"
SENDER="${TMPDIR:-/tmp}/send-fm1-va-sound-cc"
RUN=1
LAST_SENT=""

# ── Helpers ──────────────────────────────────────────────────────────────

log() { printf '%s\n' "$*" >> "$LEDGER"; }
heading() { log ""; log "## $*"; log ""; }

# answer KEY "Question" reads a free-text observation into KEY, never remembered between runs.
answer() {
  local reply=""
  printf '  %s%s%s ' "$BOLD" "$2" "$RESET"
  read -r reply || true
  printf -v "$1" '%s' "${reply:--}"
}

is_sound_controller() {
  local cc="$1"
  { ((cc >= 24 && cc <= 31)) || ((cc >= 52 && cc <= 57)) || ((cc >= 70 && cc <= 78)); }
}

# send CC VALUE [CHANNEL] sends one sound-setting Control Change, retrying or skipping on failure.
send() {
  local cc="$1" value="$2" channel="${3:-1}" output
  if ! is_sound_controller "$cc" || ((value < 0 || value > 127 || channel < 1 || channel > 16)); then
    printf '%sRefusing CC %s = %s on channel %s.%s\n' "$RED" "$cc" "$value" "$channel" "$RESET" >&2
    exit 1
  fi
  while true; do
    if output=$("$SENDER" "$FM1_DEST" "$channel" "$cc" "$value" 2>&1); then
      LAST_SENT="$output"
      printf '  %s→ %s%s\n' "$GREEN" "$output" "$RESET"
      return 0
    fi
    warn "send failed: $output"
    if ! confirm "Try again?"; then
      LAST_SENT="(failed: $output)"
      return 0
    fi
  done
}

# held_send CC VALUE [CHANNEL] waits while the human holds a note, then sends.
held_send() {
  pause "Hold a note on the FM1, then press Enter to send CC $1 = $2${3:+ on channel $3}"
  send "$@"
}

erase_reminder() {
  step "Start from a freshly erased test preset: step PRESETS away and back, then EDIT →"
  step "Erase Preset → confirm → VA. Do not press SAVE."
  pause "Press Enter once the test preset is erased to VA"
}

# A section runs unless the run resumes after it; a skipped one still counts its stages.
section() {
  local name="$1" stages="$2" index
  index=$(section_index "$name")
  if ((index < START_INDEX)); then
    _STAGE_INDEX=$((_STAGE_INDEX + stages))
    return 1
  fi
  return 0
}

# ── Stages ──────────────────────────────────────────────────────────────

banner "FM-1+VA controller tests"

if section prep 1; then
  stage "Preparation"
  say "This runs docs/fm1-va-controller-tests.md against your FM1. Keep the plan open beside it."
  say "It sends only CC 24–31, 52–57 and 70–78, never the FM1's own buttons (85–119), never SysEx."
  printf '\n'
  step "On the FM1, open GLOBE and read the version under About, at the end."
  step "On FM-1+VA's own Presets page, press “Save a backup” and keep the .syx file."
  note "  Close that tab afterwards, so it doesn't hold the FM1's MIDI port."
  step "Check GLOBE: MIDI Channel All, FX Channel 2, Ext Ctrl CC7 Vol On."
  step "Close the editor and every other MIDI app."
  printf '\n'
  pause "Press Enter once the backup is saved and GLOBE is at its defaults"
fi

stage "Sender and FM1"
ask FIRMWARE "FM-1+VA version from About (for example FM-1_093):"
write_env FIRMWARE "$FIRMWARE"
ask SETUP "Computer and USB connection (for example MacBook Pro, USB-C cable):"
write_env SETUP "$SETUP"
say "Building the sender…"
clang -o "$SENDER" scripts/send-fm1-va-sound-cc.c -framework CoreMIDI -framework CoreFoundation
printf '\n'
"$SENDER" list | sed 's/^/    /'
printf '\n'
note "On macOS the FM1 is listed as USB Composite Device."
ask FM1_DEST "Number of the FM1's destination:"
write_env FM1_DEST "$FM1_DEST"
DEST_NAME=$("$SENDER" list | awk -v n="$FM1_DEST" '$1 == n { $1 = ""; sub(/^ /, ""); print }')
[[ -n "$DEST_NAME" ]] || { warn "No destination $FM1_DEST."; exit 1; }
[[ "$DEST_NAME" == "USB Composite Device" ]] || warn "That is “$DEST_NAME”, not USB Composite Device."
confirm "Send to “$DEST_NAME”?" || exit 1
LEDGER=$(_existing LEDGER || true)
if [[ -z "$LEDGER" || ! -f "$LEDGER" ]] || ! confirm "Keep adding to $LEDGER?"; then
  LEDGER="$LEDGER_DIR/fm1-va-controller-$(date +%Y-%m-%d-%H%M).md"
  write_env LEDGER "$LEDGER"
  {
    printf '# FM-1+VA controller test run\n\n'
    printf -- '- Started: %s\n' "$(date '+%Y-%m-%d %H:%M')"
    printf -- '- Firmware: %s\n' "$FIRMWARE"
    printf -- '- Setup: %s\n' "$SETUP"
    printf -- '- Destination: %s %s\n' "$FM1_DEST" "$DEST_NAME"
  } > "$LEDGER"
fi
log ""
log "Session from $(date '+%Y-%m-%d %H:%M'), resuming at $FROM_SECTION${FROM_CC:+:$FROM_CC}."

# ── V1: defaults of a new Virtual Analog preset ──────────────────────────

v1_rows() {
  local row value
  for row in "$@"; do
    answer value "$row:"
    log "- $row: $value"
  done
}

if section V1 3; then
  stage "V1 · New preset defaults: oscillator"
  say "Select the test preset, 097 (bank D, slot 1) unless the preset pack holds it."
  erase_reminder
  heading "V1 · Defaults of a new Virtual Analog preset"
  say "Before sending anything, open EDIT and read each row."
  v1_rows Waveform Super Detune Drift Sub Noise PWM Level Mono

  stage "V1 · New preset defaults: filter"
  v1_rows "Filter Type" Cutoff Resonance "Filter Envelope" "Filter Decay" "Filter Shape" \
    "Filter Velocity" "Filter Key Tracking" "LFO to Cutoff"

  stage "V1 · New preset defaults: LFO and Envelope"
  v1_rows "LFO Wave" "LFO Speed" "LFO Pitch Mod Depth" "LFO Amp Mod Depth" "LFO Delay" \
    "LFO Pitch Sensitivity" "LFO Sync" "Envelope switch (On/Off)" Attack Decay Sustain Release
fi

# ── V2: each CC reaches its row ──────────────────────────────────────────


v2_controller() {
  local cc="$1" name="$2" value shown held dot
  stage "V2 · CC $cc, $name (run $RUN)"
  say "Expected row: $name. Each value is sent while you hold a note."
  for value in 0 64 127; do
    held_send "$cc" "$value"
    answer shown "Row and value the screen shows:"
    log "- CC $cc = $value: \`$LAST_SENT\` → $shown"
  done
  answer held "Did the held note change at once each time? (y/n, notes):"
  answer dot "On HOME, is there a dot after the preset's name? (y/n):"
  log "- CC $cc, held note changed: $held; dot on HOME: $dot"
}

if section V2 23; then
  heading "V2 · Each CC reaches its row (run 1)"
  started=""
  [[ "$FROM_SECTION" == V2 && -n "$FROM_CC" ]] || started=yes
  first=yes
  for entry in $V2_CONTROLLERS; do
    cc="${entry%%:*}"
    if [[ -z "$started" ]]; then
      if [[ "$cc" == "$FROM_CC" ]]; then started=yes; else _STAGE_INDEX=$((_STAGE_INDEX + 1)); continue; fi
    fi
    if [[ -n "$first" ]]; then
      _clear
      erase_reminder
      first=""
    fi
    [[ "$cc" == 70 ]] && warn "From here on the Envelope controllers switch the Envelope on."
    v2_controller "$cc" "$(printf '%s' "${entry#*:}" | tr _ ' ')"
  done
fi

# ── V3: list settings ────────────────────────────────────────────────────

v3_controller() {
  local cc="$1" name="$2" value shown
  stage "V3 · List setting CC $cc, $name (run $RUN)"
  say "Values at the edges of four equal bands. Record the choice by the name on screen."
  for value in 31 32 63 64 95 96; do
    send "$cc" "$value"
    answer shown "Choice shown:"
    log "- CC $cc = $value: \`$LAST_SENT\` → $shown"
  done
}

if section V3 3; then
  _clear
  erase_reminder
  heading "V3 · List settings (run 1)"
  v3_controller 24 Waveform
  v3_controller 31 "Filter Type"
  v3_controller 56 "Filter Key Tracking"
fi

# ── V4: continuous scaling ───────────────────────────────────────────────

v4_controller() {
  local cc="$1" name="$2" value shown
  stage "V4 · Scaling of CC $cc, $name"
  say "Record each value exactly as shown${3:+ ($3)}."
  for value in 0 1 2 32 63 64 65 96 126 127; do
    send "$cc" "$value"
    answer shown "Value shown:"
    log "- CC $cc = $value: \`$LAST_SENT\` → $shown"
  done
}

if section V4 3; then
  _clear
  erase_reminder
  heading "V4 · Continuous scaling"
  v4_controller 25 Super
  v4_controller 53 "Filter Decay"
  v4_controller 74 Cutoff "it shows hertz"
fi

# ── V5: the Envelope switch ──────────────────────────────────────────────

if section V5 1; then
  stage "V5 · The Envelope switch"
  erase_reminder
  heading "V5 · The Envelope switch"
  step "Press ENV, or open the Envelope group."
  answer before "Is Envelope On or Off?"
  log "- After the erase, Envelope: $before"
  send 73 64
  answer after "Is Envelope now On, and does Attack show the new value?"
  log "- CC 73 = 64: \`$LAST_SENT\` → $after"
  step "Step PRESETS away and back without SAVE."
  answer back "Did the Envelope switch return to the stored preset's own setting?"
  log "- After stepping away and back: $back"
fi

# ── V6: channels and preset kinds ────────────────────────────────────────

if section V6 3; then
  stage "V6 · The FX Channel"
  erase_reminder
  heading "V6 · Channels and preset kinds"
  send 25 127 2
  answer seen "Did anything change? (expected: nothing, CCs above 23 are ignored there):"
  log "- CC 25 = 127 on channel 2: \`$LAST_SENT\` → $seen"

  stage "V6 · A fixed MIDI Channel"
  step "In GLOBE, set MIDI Channel to 1."
  pause "Press Enter once MIDI Channel is 1"
  send 25 0 3
  answer seen "On channel 3: did anything change? (expected: nothing):"
  log "- MIDI Channel 1, CC 25 = 0 on channel 3: \`$LAST_SENT\` → $seen"
  send 25 0 1
  answer seen "On channel 1: did Super change?"
  log "- MIDI Channel 1, CC 25 = 0 on channel 1: \`$LAST_SENT\` → $seen"
  step "In GLOBE, set MIDI Channel back to All."
  pause "Press Enter once MIDI Channel is All again"

  stage "V6 · An FM preset"
  step "Select an FM preset."
  pause "Press Enter once an FM preset is selected"
  for pair in 24:127 31:127 57:127; do
    send "${pair%%:*}" "${pair#*:}"
    answer seen "Did anything change, or a dot appear? (expected: neither):"
    log "- FM preset, CC ${pair%%:*} = ${pair#*:}: \`$LAST_SENT\` → $seen"
  done
  send 74 0
  answer seen "What did CC 74 (Brightness) do?"
  log "- FM preset, CC 74 = 0: \`$LAST_SENT\` → $seen"
  step "Step PRESETS away and back to discard it."
  pause
fi

# ── V8: fast changes ─────────────────────────────────────────────────────

v8_sweep() {
  local cc="$1" name="$2" value failed=0 seen ending
  stage "V8 · A fast sweep of CC $cc, $name"
  say "Sends 0 to 127 and back to 0, 256 messages, as a slider drag would."
  pause "Hold a note on the FM1, then press Enter to start the sweep"
  for value in $(seq 0 127) $(seq 127 -1 0); do
    "$SENDER" "$FM1_DEST" 1 "$cc" "$value" >/dev/null 2>&1 || failed=$((failed + 1))
  done
  say "Sweep sent, $failed failed."
  answer seen "Any crackle, stuck note, or freeze? (notes):"
  answer ending "Value the screen ends on (expected: its lowest, from 0):"
  log "- CC $cc swept 0→127→0 (256 messages, $failed failed): $seen; ends on: $ending"
}

if section V8 2; then
  _clear
  erase_reminder
  heading "V8 · Fast changes"
  v8_sweep 74 Cutoff
  v8_sweep 25 Super
fi

# ── Repeatability ────────────────────────────────────────────────────────

if section repeat 6; then
  stage "Repeat run: power cycle"
  step "Switch the FM1 off and on."
  pause "Press Enter once the FM1 is back on"
  erase_reminder
  heading "Repeat run after a power cycle"
  RUN=2
  heading "V2 · Each CC reaches its row (run 2)"
  v2_controller 24 Waveform
  v2_controller 25 Super
  v2_controller 31 "Filter Type"
  v2_controller 74 Cutoff
  heading "V3 · List settings (run 2)"
  v3_controller 24 Waveform
  RUN=1
fi

# ── V7: the editor's patch over a Virtual Analog preset ──────────────────

if section V7 3; then
  stage "V7 · Store a Virtual Analog test preset"
  erase_reminder
  heading "V7 · The editor's patch over a Virtual Analog preset"
  send 24 127
  log "- Waveform to Square: \`$LAST_SENT\`"
  warn "Next you press SAVE: it stores this Virtual Analog preset over the test preset."
  note "  Clean-up puts the test preset back from your backup."
  if confirm "Have you pressed SAVE on the FM1?"; then
    write_env V7_SAVED yes
    step "Step PRESETS away and back."
    answer still "Does it still play as a Virtual Analog preset?"
    log "- Saved; after stepping away and back: $still"

    stage "V7 · Send a patch from the editor"
    step "Open the editor, check Settings names Baud Girl's firmware, and switch MIDI on."
    step "Search, then click one patch under Other DX7 patch banks, once."
    step "Wait until the MIDI log shows it sent as parameter changes."
    pause "Press Enter once it has been sent"
    answer plays "Does the FM1 now play the DX7 patch?"
    answer kind "Does EDIT show an FM or a Virtual Analog preset?"
    answer dot "Is there a dot after the preset's name?"
    log "- After the editor's patch: plays it: $plays; EDIT shows: $kind; dot: $dot"

    stage "V7 · Step away"
    step "Step PRESETS away and back without SAVE."
    answer stored "Is the stored Virtual Analog preset back, or is it now an FM preset?"
    log "- After stepping away and back: $stored"
    step "Close the editor."
    pause
  else
    log "- Not saved, so V7 was skipped."
    _STAGE_INDEX=$((_STAGE_INDEX + 2))
  fi
fi

# ── Clean-up ─────────────────────────────────────────────────────────────

if section cleanup 1; then
  stage "Clean-up"
  step "Step PRESETS away from the test preset."
  if [[ "$(_existing V7_SAVED || true)" == yes ]]; then
    step "On FM-1+VA's own Presets page, use “Put a backup back” with the file from the start."
    note "  It rewrites only the presets that differ from the backup."
  else
    note "Nothing was saved, so the backup isn't needed unless a preset was saved by mistake."
  fi
  step "Check that GLOBE's MIDI Channel is All."
  pause "Press Enter once the FM1 is back as it was"
  heading "Clean-up"
  log "- Done $(date '+%Y-%m-%d %H:%M')."
fi

finish
say "Ledger: $LEDGER"
say "Send the ledger back to have the results written into docs/fm1-research.md."
printf '\n'
